// The 50 lessons. `build-lessons.mjs` turns each entry into a static HTML page.
// `concept` / `watch` / callouts are trusted HTML written here (never user input).
// Every `sql` is executed by test/lessons.test.mjs, so a broken lesson fails the build.

const L = (level, slug, title, blurb, sql, concept, watch, extra = {}) => ({ level, slug, title, blurb, sql, concept, watch, ...extra });

export const LESSONS = [
  // ───────────────────────────── BEGINNER (1–16)
  L('beginner', 'select-columns', 'Picking columns with SELECT',
    'Ask a table for just the columns you care about.',
    'SELECT name, city\nFROM customers;',
    '<p>A <b>table</b> is a grid: every <b>row</b> is one thing (one customer) and every <b>column</b> is one fact about it (name, city…).</p><p><code>FROM customers</code> says <i>which table</i> to read. <code>SELECT name, city</code> says <i>which columns</i> to keep. The database always reads <code>FROM</code> first, then trims to the columns you named.</p>',
    ['All 20 customer rows fly out of the <b>customers</b> table (pink).', 'In the SELECT step the chips shrink to just <code>name</code> and <code>city</code> — the other columns are cut away.'],
    { tip: 'Column order in SELECT is the order you get back. Try <code>SELECT city, name</code>.' }),

  L('beginner', 'select-star', 'SELECT * — every column',
    'The star is a shortcut for "all columns".',
    'SELECT *\nFROM departments;',
    '<p><code>*</code> means "every column, in table order". It is handy for peeking at a table you have never seen.</p><p>Because nothing is being removed, the SELECT step has nothing to cut: rows go straight from the table to the result.</p>',
    ['Six department rows slide out of the <b>departments</b> table and land in the result unchanged.'],
    { warn: 'In real applications avoid <code>SELECT *</code>: it drags every column across the network and breaks when someone adds a column.' }),

  L('beginner', 'aliases', 'Renaming columns with AS',
    'Give result columns friendlier names.',
    'SELECT name AS customer,\n       city AS home_town\nFROM customers;',
    '<p><code>AS</code> gives a column (or later, a table) an <b>alias</b>: a nickname used in the output. The data does not change — only the label does.</p><p>Aliases become essential once queries compute values or join tables that have columns with the same name.</p>',
    ['The result has the same cells as lesson 1, but the column headers read <code>customer</code> and <code>home_town</code>.'],
    { tip: 'Open the <b>Table</b> tab to compare the headers with the original column names.' }),

  L('beginner', 'where-basic', 'Filtering rows with WHERE',
    'Keep only the rows that satisfy a condition.',
    "SELECT name, city\nFROM customers\nWHERE country = 'USA';",
    '<p><code>WHERE</code> tests <b>every row</b> against a condition. Rows where the condition is <b>true</b> stay; all others are discarded.</p><p>Notice the order: <code>FROM</code> loads the rows, <code>WHERE</code> filters them, and only then does <code>SELECT</code> pick columns.</p>',
    ['All 20 rows arrive, then the rows that fail <code>country = \'USA\'</code> turn red and <b>fall away</b>.', 'Only the survivors reach the SELECT step.'],
    { tip: 'Text values go in single quotes: <code>\'USA\'</code>. Double quotes are for identifiers.' }),

  L('beginner', 'where-and-or', 'Combining conditions: AND, OR',
    'Build richer filters with AND, OR and parentheses.',
    'SELECT name, price, stock\nFROM products\nWHERE category_id = 1\n  AND (price > 150 OR stock < 50);',
    '<p><code>AND</code> needs <b>both</b> sides to be true. <code>OR</code> needs <b>at least one</b>. When you mix them, use parentheses — <code>AND</code> binds tighter than <code>OR</code>, so without brackets the meaning changes.</p><p>Here: electronics (<code>category_id = 1</code>) that are either expensive <i>or</i> running low.</p>',
    ['Products that are not electronics fall first, then electronics that are neither pricey nor low in stock.'],
    { warn: 'Try removing the parentheses and watch the result change — a classic source of bugs.' }),

  L('beginner', 'order-by', 'Sorting with ORDER BY',
    'Put the rows in a meaningful order.',
    'SELECT name, price\nFROM products\nORDER BY price DESC;',
    '<p>Without <code>ORDER BY</code> a database may return rows in any order. <code>ORDER BY price DESC</code> sorts from the highest price down; <code>ASC</code> (the default) goes low to high.</p><p>Sorting happens <b>near the end</b>, after filtering and after the SELECT list is computed.</p>',
    ['Watch the chips physically <b>slide past each other</b> into their sorted positions.'],
    { tip: 'Sort by several columns: <code>ORDER BY category_id, price DESC</code>.' }),

  L('beginner', 'limit-offset', 'Top-N with LIMIT and OFFSET',
    'Take just a slice of the sorted rows.',
    'SELECT name, price\nFROM products\nORDER BY price DESC\nLIMIT 5 OFFSET 2;',
    '<p><code>LIMIT 5</code> keeps at most five rows. <code>OFFSET 2</code> first skips two. Together they page through results: "page 2 of the price list".</p><p>LIMIT only makes sense after <code>ORDER BY</code> — otherwise "the first five" is arbitrary.</p>',
    ['After sorting, the first two rows and everything beyond row seven are cut away.'],
    {}),

  L('beginner', 'distinct', 'Removing duplicates with DISTINCT',
    'Each different value once.',
    'SELECT DISTINCT country\nFROM customers\nORDER BY country;',
    '<p>Several customers share a country, so <code>SELECT country</code> would repeat values. <code>DISTINCT</code> collapses identical rows into one.</p>',
    ['Duplicate chips <b>merge into</b> the first chip with the same value.'],
    { tip: '<code>SELECT DISTINCT a, b</code> removes duplicate <i>pairs</i>, not duplicate values of each column.' }),

  L('beginner', 'like', 'Pattern matching with LIKE',
    'Find text that looks like something.',
    "SELECT name\nFROM customers\nWHERE name LIKE 'M%'\n   OR name LIKE '%son';",
    '<p><code>LIKE</code> compares text to a pattern. <code>%</code> stands for any run of characters and <code>_</code> for exactly one character.</p><ul><li><code>\'M%\'</code> — starts with M</li><li><code>\'%son\'</code> — ends with "son"</li><li><code>\'%an%\'</code> — contains "an"</li></ul>',
    ['Rows whose names match neither pattern are dropped by WHERE.'],
    {}),

  L('beginner', 'in-between', 'IN and BETWEEN',
    'Shorter ways to write common filters.',
    'SELECT name, price\nFROM products\nWHERE category_id IN (2, 5)\n  AND price BETWEEN 15 AND 40;',
    '<p><code>x IN (2, 5)</code> is shorthand for <code>x = 2 OR x = 5</code>. <code>x BETWEEN 15 AND 40</code> means <code>x &gt;= 15 AND x &lt;= 40</code> — both ends are <b>included</b>.</p>',
    ['Books (2) and toys (5) survive the first test; then the price range removes the rest.'],
    {}),

  L('beginner', 'null', 'NULL — the missing value',
    'NULL means "unknown", and it behaves strangely on purpose.',
    'SELECT name, email\nFROM customers\nWHERE email IS NULL;',
    '<p><code>NULL</code> is not zero and not an empty string — it means <b>no value</b>. Because the value is unknown, <code>email = NULL</code> is never true (not even for another NULL). You must ask <code>IS NULL</code> or <code>IS NOT NULL</code>.</p>',
    ['Look for the italic <i>NULL</i> cell in the <b>customers</b> table above; only that row survives the filter.'],
    { warn: '<code>WHERE email = NULL</code> returns nothing — a very common beginner mistake.' }),

  L('beginner', 'expressions', 'Calculated columns',
    'Compute new values on the fly.',
    'SELECT name,\n       price,\n       ROUND(price * 1.2, 2) AS price_with_tax\nFROM products\nLIMIT 8;',
    '<p>SELECT can contain <b>expressions</b>: arithmetic (<code>+ - * /</code>), functions like <code>ROUND</code>, <code>UPPER</code>, <code>LENGTH</code>… The result is computed per row; the stored table is untouched.</p><p>Computed columns have no source table, so they appear in a neutral grey instead of a table colour.</p>',
    ['A new grey cell appears on each chip in the SELECT step.'],
    {}),

  L('beginner', 'count', 'Counting rows with COUNT',
    'Collapse many rows into one number.',
    "SELECT COUNT(*) AS delivered_orders\nFROM orders\nWHERE status = 'delivered';",
    '<p>An <b>aggregate function</b> summarises many rows into one. <code>COUNT(*)</code> counts rows. Because a WHERE comes first, this counts only the delivered orders.</p>',
    ['Surviving rows stack up and then <b>merge into a single chip</b> holding the count.'],
    { tip: '<code>COUNT(column)</code> skips NULLs; <code>COUNT(*)</code> counts every row.' }),

  L('beginner', 'sum-avg', 'SUM, AVG, MIN and MAX',
    'More ways to summarise a column.',
    'SELECT SUM(quantity) AS units_sold,\n       AVG(unit_price) AS avg_price,\n       MIN(unit_price) AS cheapest,\n       MAX(unit_price) AS priciest\nFROM order_items;',
    '<p>The classic aggregates: <code>SUM</code> adds, <code>AVG</code> averages, <code>MIN</code> / <code>MAX</code> pick the extremes. NULLs are ignored. With no GROUP BY, the <b>whole table is one group</b>, so you get exactly one row.</p>',
    ['All order_items rows collapse into one result row containing four numbers.'],
    {}),

  L('beginner', 'group-by', 'Grouping with GROUP BY',
    'One summary row per group.',
    'SELECT country, COUNT(*) AS customers\nFROM customers\nGROUP BY country\nORDER BY customers DESC;',
    '<p><code>GROUP BY country</code> sorts rows into <b>buckets</b>: one bucket per distinct country. The aggregate then runs <i>inside each bucket</i>.</p><p>Every column in SELECT must either be in the GROUP BY or be inside an aggregate — otherwise SQL cannot know which row\'s value to show.</p>',
    ['Chips travel into labelled buckets (one per country), then each bucket collapses into one row with its count.'],
    { warn: 'Try <code>SELECT name, COUNT(*) FROM customers GROUP BY country</code> and read the error message.' }),

  L('beginner', 'insert', 'Adding rows with INSERT',
    'Create new rows in a table.',
    "INSERT INTO categories (name)\nVALUES ('Pets'), ('Garden');",
    '<p><code>INSERT INTO table (columns) VALUES (…)</code> appends rows. Columns you skip get their default (usually NULL) — here the <code>id</code> is filled in automatically with the next free number.</p><p>Everything lives in your browser\'s memory. <b>Reset</b> or a refresh restores the original data.</p>',
    ['Two green chips join the end of <b>categories</b>, then the table above flashes the new rows.'],
    { tip: 'Each table is capped at 50 rows so the animations stay smooth.' }),

  // ───────────────────────────── INTERMEDIATE (17–34)
  L('intermediate', 'update', 'Changing rows with UPDATE',
    'Modify existing values.',
    'UPDATE products\nSET stock = stock + 100\nWHERE stock < 50;',
    '<p><code>UPDATE … SET column = value WHERE …</code> rewrites cells in rows that match. <b>Without WHERE it changes every row.</b></p><p>The new value can use the old one: <code>stock + 100</code>.</p>',
    ['Matching rows glow red, then the changed cells pulse amber while the others stay dimmed.'],
    { warn: 'Always write the WHERE first, run it as a SELECT to check which rows match, then turn it into an UPDATE.' }),

  L('intermediate', 'delete', 'Removing rows with DELETE',
    'Take rows out of a table.',
    "DELETE FROM orders\nWHERE status = 'cancelled';",
    '<p><code>DELETE FROM table WHERE …</code> removes matching rows. No WHERE means <b>all rows go</b>.</p><p>In a real database, deleting an order that other tables (like <code>order_items</code>) still point to would be blocked or cascade — this playground does not enforce that, so you can experiment freely.</p>',
    ['Cancelled orders are marked, then physically <b>drop out</b> of the table.'],
    {}),

  L('intermediate', 'alter-table', 'Changing structure with ALTER TABLE',
    'Add, drop or rename columns.',
    'ALTER TABLE customers\nADD COLUMN vip BOOLEAN DEFAULT false;',
    '<p>INSERT/UPDATE/DELETE change <b>rows</b>. <code>ALTER TABLE</code> changes the table\'s <b>shape</b>: <code>ADD COLUMN</code>, <code>DROP COLUMN</code>, <code>RENAME COLUMN a TO b</code>.</p><p>Existing rows receive the default value for a new column (NULL if none).</p>',
    ['Every row gains a new cell (highlighted), and the customers card above flashes.'],
    { tip: 'Afterwards try <code>UPDATE customers SET vip = true WHERE country = \'USA\'</code>.' }),

  L('intermediate', 'inner-join', 'INNER JOIN — connecting tables',
    'Follow a foreign key to combine two tables.',
    'SELECT c.name, o.id AS order_id, o.order_date\nFROM customers c\nINNER JOIN orders o ON o.customer_id = c.id;',
    '<p>Data is split across tables to avoid repeating it. An order stores only <code>customer_id</code> — a <b>foreign key</b> pointing at <code>customers.id</code>. A <b>JOIN</b> glues related rows back together.</p><p><code>ON o.customer_id = c.id</code> is the matching rule: a customer row and an order row are paired when this is true. <code>c</code> and <code>o</code> are table aliases.</p>',
    ['Pink customer chips and red order chips land side by side.', 'Each matching pair <b>merges into one wide row</b> that carries both colours.', 'Customers without any order have nothing to pair with — INNER JOIN drops them.'],
    { tip: 'The colours tell you where every cell came from: pink = customers, red = orders.' }),

  L('intermediate', 'join-where', 'Filtering joined rows',
    'Join first, filter after.',
    "SELECT c.name, o.id, o.status\nFROM customers c\nJOIN orders o ON o.customer_id = c.id\nWHERE o.status = 'pending'\nORDER BY c.name;",
    '<p><code>JOIN</code> alone is shorthand for <code>INNER JOIN</code>. The WHERE runs <b>after</b> the join, on the combined rows — so it can use columns from either table.</p>',
    ['The merged rows form first; then the non-pending ones fall away.'],
    {}),

  L('intermediate', 'left-join', 'LEFT JOIN — keep everything on the left',
    'Do not lose rows that have no partner.',
    'SELECT c.name, o.id AS order_id\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id;',
    '<p>An INNER JOIN silently drops rows with no match. A <b>LEFT JOIN</b> keeps <b>every row of the left table</b>; where the right side has no partner its columns are filled with <code>NULL</code>.</p>',
    ['Two customers (Sam Carter, Tara Brooks) have no orders. They stay in the result, with <i>NULL</i> in the order column.'],
    {}),

  L('intermediate', 'anti-join', 'Finding what is missing (anti-join)',
    'LEFT JOIN + IS NULL = "rows with no match".',
    'SELECT c.name\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nWHERE o.id IS NULL;',
    '<p>A very common question: <i>which customers never ordered?</i> Do a LEFT JOIN, then keep only rows where the right side came back NULL. Those are exactly the unmatched left rows.</p>',
    ['Step 1 builds the LEFT JOIN (with NULLs for non-buyers). Step 2: WHERE throws away everyone who <i>did</i> match.'],
    { tip: 'The same idea answers "products never sold": <code>products LEFT JOIN order_items … WHERE order_items.id IS NULL</code>.' }),

  L('intermediate', 'right-join', 'RIGHT JOIN — keep everything on the right',
    'Mirror image of LEFT JOIN.',
    'SELECT d.name AS department, e.name AS employee\nFROM employees e\nRIGHT JOIN departments d ON e.dept_id = d.id;',
    '<p>RIGHT JOIN keeps every row of the <b>right</b> table. Here that is <code>departments</code> — so a department with no employees (Legal) still appears, with a NULL employee.</p><p>Most people just swap the table order and use LEFT JOIN; both are equivalent.</p>',
    ['Watch Legal stay behind with NULLs while all other departments pair up with their employees.'],
    {}),

  L('intermediate', 'full-join', 'FULL JOIN — keep everything',
    'Keep unmatched rows from both sides.',
    'SELECT d.name AS department, e.name AS employee, e.salary\nFROM departments d\nFULL JOIN employees e\n  ON e.dept_id = d.id AND e.salary > 150000;',
    '<p>FULL JOIN = LEFT + RIGHT: unmatched rows from <b>both</b> tables survive, padded with NULLs.</p><p>The ON condition here has an extra rule (<code>salary &gt; 150000</code>), so only high earners match their department. Everyone else becomes "employee with no department"; departments without a high earner become "department with no employee".</p>',
    ['Three kinds of rows appear in the result: matched pairs, department-only rows, employee-only rows.'],
    { warn: 'Not every database supports FULL JOIN (MySQL does not). It is part of the SQL standard.' }),

  L('intermediate', 'cross-join', 'CROSS JOIN — every combination',
    'Pair every row with every row.',
    'SELECT c.name AS category, s.name AS supplier\nFROM categories c\nCROSS JOIN suppliers s;',
    '<p>A CROSS JOIN has <b>no ON condition</b>. Each of the 6 categories is paired with each of the 6 suppliers: 6 × 6 = 36 rows. It is the raw material of every other join — a join is a cross join <i>plus a filter</i>.</p>',
    ['The result chips multiply: each category chip fans out into six.'],
    { warn: 'Accidental cross joins (a forgotten ON) are the #1 cause of "my query returned millions of rows".' }),

  L('intermediate', 'self-join', 'Self join — a table joined to itself',
    'Employees and their managers live in the same table.',
    'SELECT e.name AS employee, m.name AS manager\nFROM employees e\nLEFT JOIN employees m ON e.manager_id = m.id;',
    '<p><code>employees.manager_id</code> points at another row of <code>employees</code>. To read both sides we use the table <b>twice</b> with different aliases: <code>e</code> (the employee) and <code>m</code> (their manager).</p><p>The CEO has no manager (<code>manager_id</code> is NULL), so a LEFT JOIN keeps her with a NULL manager.</p>',
    ['Two lanes both show employee rows — same table, two roles.'],
    {}),

  L('intermediate', 'three-table-join', 'Joining three tables',
    'Chain joins: each ON links the next table.',
    "SELECT c.name AS customer, o.id AS order_id, e.name AS sales_rep\nFROM orders o\nJOIN customers c ON o.customer_id = c.id\nJOIN employees e ON o.employee_id = e.id\nWHERE o.status = 'delivered';",
    '<p>Start with <code>orders</code> — it holds two foreign keys (<code>customer_id</code>, <code>employee_id</code>). Each additional JOIN pulls in one more table, widening the row.</p><p>Joins run <b>left to right</b>: orders+customers first, then that result joined with employees.</p>',
    ['Two join rounds: red+blue first, then violet employees merge in.'],
    {}),

  L('intermediate', 'four-table-join', 'Joining four tables',
    'Follow the chain order_items → orders / products → categories.',
    'SELECT o.id AS order_id, p.name AS product, cat.name AS category, oi.quantity\nFROM order_items oi\nJOIN orders o ON oi.order_id = o.id\nJOIN products p ON oi.product_id = p.id\nJOIN categories cat ON p.category_id = cat.id\nWHERE oi.quantity >= 3;',
    '<p>Big questions usually span many tables. The trick is to read the foreign keys like a map: <code>order_items</code> points at <code>orders</code> and <code>products</code>; <code>products</code> points at <code>categories</code>.</p><p>Filter early (<code>WHERE oi.quantity &gt;= 3</code> could also be written in the first ON) — fewer rows to carry through each join.</p>',
    ['The row grows wider with each join: orange items, then red order, green product, lime category cells.'],
    { tip: 'Open the Analyze tab to see how the row count changes after each join.' }),

  L('intermediate', 'join-group', 'JOIN + GROUP BY',
    'Count related rows per entity.',
    'SELECT c.name, COUNT(o.id) AS orders\nFROM customers c\nLEFT JOIN orders o ON o.customer_id = c.id\nGROUP BY c.name\nORDER BY orders DESC, c.name;',
    '<p>Join first, group second. The LEFT JOIN guarantees every customer is present; <code>COUNT(o.id)</code> counts only real orders (it skips NULL), so customers without orders correctly show <b>0</b>.</p>',
    ['Customers with no orders form a bucket whose COUNT(o.id) is 0 — with <code>COUNT(*)</code> they would wrongly show 1.'],
    { warn: 'Use <code>COUNT(o.id)</code> not <code>COUNT(*)</code> after a LEFT JOIN, otherwise the NULL row is counted.' }),

  L('intermediate', 'having', 'Filtering groups with HAVING',
    'WHERE filters rows, HAVING filters groups.',
    'SELECT c.name, COUNT(*) AS orders\nFROM customers c\nJOIN orders o ON o.customer_id = c.id\nGROUP BY c.name\nHAVING COUNT(*) >= 3;',
    '<p>You cannot write <code>WHERE COUNT(*) &gt;= 3</code> — the count does not exist yet when WHERE runs. <code>HAVING</code> runs <b>after grouping</b>, so it can test aggregates.</p>',
    ['Buckets collapse into counted rows, then HAVING drops the small ones.'],
    { tip: 'Rule of thumb: row-level condition → WHERE (cheaper). Group-level condition → HAVING.' }),

  L('intermediate', 'execution-order', 'The real order of a query',
    'You write SELECT first, but SQL runs it almost last.',
    'SELECT p.name, SUM(oi.quantity) AS units\nFROM order_items oi\nJOIN products p ON oi.product_id = p.id\nWHERE oi.quantity >= 2\nGROUP BY p.name\nHAVING SUM(oi.quantity) >= 4\nORDER BY units DESC\nLIMIT 3;',
    '<p>The logical order is:</p><ol><li><b>FROM / JOIN</b> — build the working set</li><li><b>WHERE</b> — filter rows</li><li><b>GROUP BY</b> — bucket</li><li><b>HAVING</b> — filter buckets</li><li><b>SELECT</b> — compute columns</li><li><b>ORDER BY</b> — sort</li><li><b>LIMIT</b> — cut</li></ol><p>This explains why you cannot use a SELECT alias in WHERE (it does not exist yet) but you can in ORDER BY.</p>',
    ['Follow the stepper: every stage of the pipeline appears in turn.'],
    { tip: 'Open the <b>Analyze</b> tab: it numbers each clause by the order it actually runs.' }),

  L('intermediate', 'case-when', 'CASE WHEN — if/else inside SQL',
    'Turn values into categories.',
    "SELECT name,\n       price,\n       CASE\n         WHEN price < 20 THEN 'budget'\n         WHEN price < 100 THEN 'standard'\n         ELSE 'premium'\n       END AS tier\nFROM products;",
    '<p><code>CASE</code> checks conditions top to bottom and returns the first matching result. It is SQL\'s if / else-if / else, usable anywhere an expression is allowed — in SELECT, WHERE, ORDER BY, even inside aggregates.</p>',
    ['Each chip gets a computed grey <code>tier</code> cell.'],
    {}),

  L('intermediate', 'functions-coalesce', 'Handy functions & COALESCE',
    'Clean up and default values.',
    "SELECT name,\n       COALESCE(email, 'no email on file') AS contact,\n       UPPER(country) AS country,\n       LENGTH(name) AS name_length\nFROM customers;",
    '<p><code>COALESCE(a, b, …)</code> returns the first non-NULL argument — perfect for default values. <code>UPPER</code>, <code>LOWER</code>, <code>LENGTH</code>, <code>SUBSTR</code>, <code>REPLACE</code>, <code>ROUND</code>, <code>ABS</code> and more work row by row.</p>',
    ['Sam Carter has no email: COALESCE swaps the NULL for the fallback text.'],
    {}),

  // ───────────────────────────── ADVANCED (35–50)
  L('advanced', 'subquery-in', 'Subqueries with IN',
    'A query inside a query.',
    'SELECT name, price\nFROM products\nWHERE id IN (\n  SELECT product_id FROM order_items WHERE quantity >= 4\n);',
    '<p>A <b>subquery</b> is a SELECT in parentheses. Here it produces a list of product ids, and the outer query keeps products whose id is in that list. The inner query is evaluated first.</p><p>Subqueries are not animated step by step — the outer pipeline is shown, with the inner result already applied inside WHERE.</p>',
    ['Only the outer query\'s rows move; the filter uses the hidden inner result.'],
    {}),

  L('advanced', 'scalar-subquery', 'Scalar subqueries',
    'A subquery that returns one value.',
    'SELECT name, price\nFROM products\nWHERE price > (SELECT AVG(price) FROM products)\nORDER BY price DESC;',
    '<p>If a subquery returns exactly one row and one column it can be used like a plain number. Here: "products pricier than the average price".</p>',
    ['Products at or below the average fall away.'],
    {}),

  L('advanced', 'correlated-subquery', 'Correlated subqueries',
    'The inner query depends on the current outer row.',
    'SELECT e.name, e.salary, e.dept_id\nFROM employees e\nWHERE e.salary > (\n  SELECT AVG(salary) FROM employees WHERE dept_id = e.dept_id\n);',
    '<p>Inside the subquery, <code>e.dept_id</code> refers to the <b>outer row</b>. Conceptually, the inner query re-runs for every employee: "average salary of <i>my</i> department". The result is each person who earns more than their own department\'s average.</p>',
    ['Employees at or below their department average are filtered out.'],
    { warn: 'Correlated subqueries can be slow on big tables; joins or window functions often do the same work faster.' }),

  L('advanced', 'exists', 'EXISTS and NOT EXISTS',
    'Ask "is there at least one…?"',
    "SELECT c.name\nFROM customers c\nWHERE EXISTS (\n  SELECT 1 FROM orders o\n  WHERE o.customer_id = c.id AND o.status = 'cancelled'\n);",
    '<p><code>EXISTS (subquery)</code> is true when the subquery returns <b>at least one row</b>. What it selects does not matter — <code>SELECT 1</code> is a convention. Use <code>NOT EXISTS</code> for "has none".</p>',
    ['Customers with no cancelled order are dropped.'],
    { tip: 'Change it to <code>NOT EXISTS</code> to find customers who never cancelled.' }),

  L('advanced', 'derived-table', 'Derived tables (subquery in FROM)',
    'Use a query result as if it were a table.',
    'SELECT d.name, t.avg_salary\nFROM (\n  SELECT dept_id, AVG(salary) AS avg_salary\n  FROM employees\n  GROUP BY dept_id\n) t\nJOIN departments d ON d.id = t.dept_id\nORDER BY t.avg_salary DESC;',
    '<p>A subquery in <code>FROM</code> must have an alias (<code>t</code>). It is computed first, then treated like any other table. This lets you group first and join afterwards.</p>',
    ['The derived rows (grey) have no table to fly out of; they appear, then join with departments.'],
    {}),

  L('advanced', 'cte', 'Common Table Expressions (WITH)',
    'Name a subquery to make queries readable.',
    'WITH order_totals AS (\n  SELECT order_id, SUM(quantity * unit_price) AS total\n  FROM order_items\n  GROUP BY order_id\n)\nSELECT o.id, o.status, t.total\nFROM orders o\nJOIN order_totals t ON t.order_id = o.id\nWHERE t.total > 100\nORDER BY t.total DESC;',
    '<p><code>WITH name AS (query)</code> defines a temporary named result — a <b>CTE</b> — that the main query can use like a table. It reads top-down like a recipe: first compute the totals, then use them.</p>',
    ['The CTE is computed first (see the WITH row in Analyze), then joins to orders.'],
    {}),

  L('advanced', 'multi-cte', 'Chaining several CTEs',
    'Build the answer in layers.',
    'WITH order_totals AS (\n  SELECT order_id, SUM(quantity * unit_price) AS total\n  FROM order_items GROUP BY order_id\n),\ncustomer_spend AS (\n  SELECT o.customer_id, SUM(t.total) AS spend\n  FROM orders o JOIN order_totals t ON t.order_id = o.id\n  GROUP BY o.customer_id\n)\nSELECT c.name, s.spend\nFROM customer_spend s\nJOIN customers c ON c.id = s.customer_id\nORDER BY s.spend DESC\nLIMIT 5;',
    '<p>Later CTEs can read earlier ones. Layer 1: totals per order. Layer 2: spending per customer. Final query: the top five. Each layer is small and testable on its own.</p>',
    ['Only the final query\'s pipeline is animated; Analyze lists both CTEs with their row counts.'],
    {}),

  L('advanced', 'union', 'UNION and UNION ALL',
    'Stack the results of two queries.',
    "SELECT name, 'customer' AS kind FROM customers WHERE country = 'USA'\nUNION ALL\nSELECT name, 'employee' FROM employees WHERE dept_id = 2\nORDER BY name;",
    '<p><code>UNION</code> appends one result set below another (same number of columns). <code>UNION ALL</code> keeps every row; plain <code>UNION</code> also removes duplicates (slower).</p>',
    ['Two result lanes (one per query) are combined into a single list.'],
    { tip: 'Change <code>UNION ALL</code> to <code>UNION</code> and add a duplicate to see the merge.' }),

  L('advanced', 'intersect-except', 'INTERSECT and EXCEPT',
    'Rows in both — or only in the first.',
    'SELECT city FROM customers\nINTERSECT\nSELECT location FROM departments;',
    '<p><code>INTERSECT</code> keeps rows present in <b>both</b> result sets: cities where we have both a customer and a department. <code>EXCEPT</code> keeps rows from the first set that are <b>not</b> in the second.</p>',
    ['Only the matching city names survive; the others fall away.'],
    { tip: 'Replace INTERSECT with EXCEPT to get customer cities where we have no department.' }),

  L('advanced', 'window-row-number', 'Window functions: ROW_NUMBER',
    'Calculate across rows without collapsing them.',
    'SELECT name, dept_id, salary,\n       ROW_NUMBER() OVER (ORDER BY salary DESC) AS pos\nFROM employees;',
    '<p>GROUP BY squashes rows. A <b>window function</b> adds a computed column but <b>keeps every row</b>. <code>OVER (ORDER BY salary DESC)</code> defines the "window" — here the whole table sorted by salary — and <code>ROW_NUMBER()</code> numbers the rows 1, 2, 3…</p>',
    ['The rows stay put; a new <code>pos</code> cell appears on each.'],
    {}),

  L('advanced', 'window-rank', 'RANK vs DENSE_RANK',
    'What should happen when values tie?',
    'SELECT product_id, rating,\n       RANK() OVER (ORDER BY rating DESC) AS rnk,\n       DENSE_RANK() OVER (ORDER BY rating DESC) AS dense_rnk\nFROM reviews;',
    '<p>Ratings tie a lot. <code>RANK</code> gives tied rows the same number and then <b>skips</b> (1, 1, 1, 4…). <code>DENSE_RANK</code> does not skip (1, 1, 1, 2…). <code>ROW_NUMBER</code> never ties.</p><p>Add <code>PARTITION BY</code> to restart the numbering for each group: <code>OVER (PARTITION BY dept_id ORDER BY salary DESC)</code>.</p>',
    ['Compare the two grey rank columns where several reviews share a rating.'],
    {}),

  L('advanced', 'window-running-total', 'Running totals with SUM() OVER',
    'A total that grows row by row.',
    'SELECT id, order_id,\n       quantity * unit_price AS line_total,\n       SUM(quantity * unit_price) OVER (ORDER BY id) AS running_total\nFROM order_items\nWHERE id <= 12;',
    '<p>Aggregates become <b>running</b> aggregates when given an <code>OVER (ORDER BY …)</code>: each row\'s value covers "from the first row up to me".</p>',
    ['Look at the last column: each value is the previous one plus this row\'s line total.'],
    {}),

  L('advanced', 'window-lag-lead', 'LAG and LEAD — peek at neighbours',
    'Compare a row with the one before or after it.',
    'SELECT name, price,\n       LAG(price) OVER (ORDER BY price) AS next_cheaper,\n       LEAD(price) OVER (ORDER BY price) AS next_pricier\nFROM products\nWHERE category_id = 1;',
    '<p><code>LAG(x)</code> looks one row <b>back</b> in the window order; <code>LEAD(x)</code> one row <b>forward</b>. The first/last rows have no neighbour, so they get NULL. Handy for "change since last period".</p>',
    ['The cheapest product has NULL for next_cheaper; the priciest has NULL for next_pricier.'],
    {}),

  L('advanced', 'window-moving-average', 'Moving averages with window frames',
    'Limit the window to nearby rows.',
    'SELECT id, quantity,\n       AVG(quantity) OVER (\n         ORDER BY id\n         ROWS BETWEEN 2 PRECEDING AND CURRENT ROW\n       ) AS moving_avg\nFROM order_items\nWHERE id <= 15;',
    '<p>A <b>frame</b> narrows the window around the current row. <code>ROWS BETWEEN 2 PRECEDING AND CURRENT ROW</code> averages this row and the two before it — a 3-row moving average that smooths noisy data.</p>',
    ['The first two rows average fewer values because the frame runs off the start.'],
    {}),

  L('advanced', 'recursive-cte', 'Recursive CTEs — walking a hierarchy',
    'Follow manager → report → report… to any depth.',
    'WITH RECURSIVE chain(id, name, depth) AS (\n  SELECT id, name, 0\n  FROM employees WHERE manager_id IS NULL\n  UNION ALL\n  SELECT e.id, e.name, chain.depth + 1\n  FROM employees e\n  JOIN chain ON e.manager_id = chain.id\n)\nSELECT * FROM chain\nORDER BY depth, name;',
    '<p>A recursive CTE has two parts joined by <code>UNION ALL</code>: an <b>anchor</b> (start at the CEO, depth 0) and a <b>recursive step</b> that joins the previous round\'s rows to find their direct reports (depth + 1). It repeats until a round finds nothing new.</p><p>This is how you query org charts, category trees and folder structures.</p>',
    ['The result lists the CEO at depth 0, their reports at depth 1, and so on down the tree.'],
    { warn: 'Always make sure the recursion can end — a cycle in the data would loop forever (the playground stops after 1000 rounds).' }),

  L('advanced', 'capstone', 'Putting it all together',
    'CTEs + joins + grouping + window ranking in one report.',
    'WITH order_totals AS (\n  SELECT order_id, SUM(quantity * unit_price) AS total\n  FROM order_items\n  GROUP BY order_id\n),\ncustomer_spend AS (\n  SELECT c.id, c.name, c.country, SUM(t.total) AS spend\n  FROM customers c\n  JOIN orders o ON o.customer_id = c.id\n  JOIN order_totals t ON t.order_id = o.id\n  GROUP BY c.id, c.name, c.country\n)\nSELECT name, country, spend,\n       RANK() OVER (ORDER BY spend DESC) AS spend_rank\nFROM customer_spend\nORDER BY spend_rank\nLIMIT 8;',
    '<p>A realistic report: <i>who are our top spenders?</i></p><ol><li>CTE 1 totals every order.</li><li>CTE 2 joins customers → orders → totals and sums per customer.</li><li>The final query ranks customers with a window function and keeps the top eight.</li></ol><p>You now know every ingredient. Open the playground and answer your own questions!</p>',
    ['A tour of the whole pipeline: join, rank, sort, limit.'],
    { tip: 'Challenge: rank customers <i>within each country</i> using <code>PARTITION BY country</code>.' }),
];

export const LEVELS = {
  beginner: { name: 'Beginner', blurb: 'Read, filter, sort, summarise — and add your first rows.' },
  intermediate: { name: 'Intermediate', blurb: 'Joins in every flavour, grouping, changing data and the real order of a query.' },
  advanced: { name: 'Advanced', blurb: 'Subqueries, CTEs, set operations, window functions and recursion.' },
};
